--Patente
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (1,'GESTION','','tipo_generacion','string','Automatica',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (1,'GESTION','','tiene_formulario','string','No',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (1,'GESTION','','permite_excepción','string','No',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (1,'GESTION','','URL_excepcion','string','www.google.com',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (1,'GESTION','','URL_ejecucion','string','/api/EmpresaObligacion/{id}/ejecutar',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
--1.5x1000
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (2,'GESTION','','tipo_generacion','string','Automatica',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (2,'GESTION','','tiene_formulario','string','No',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (2,'GESTION','','permite_excepción','string','No',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (2,'GESTION','','URL_excepcion','string','www.google.com',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (2,'GESTION','','URL_ejecucion','string','/api/EmpresaObligacion/{id}/ejecutar',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
--Uso de Suelo
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (3,'GESTION','','tipo_generacion','string','Automatica',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (3,'GESTION','','tiene_formulario','string','No',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (3,'GESTION','','permite_excepción','string','Si',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (3,'GESTION','','URL_excepcion','string','www.google.com',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (3,'GESTION','','URL_ejecucion','string','/api/FormularioObligacion/{id}/ejecutar',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
--Dimensiones Mínimas
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (4,'GESTION','','tipo_generacion','string','Automatica',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (4,'GESTION','','tiene_formulario','string','No',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (4,'GESTION','','permite_excepción','string','Si',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (4,'GESTION','','URL_excepcion','string','www.google.com',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (4,'GESTION','','URL_ejecucion','string','/api/FormularioObligacion/{id}/ejecutar',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
--Interagua
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (5,'GESTION','','tipo_generacion','string','Por tramite',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (5,'GESTION','','tiene_formulario','string','Si',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (5,'GESTION','','permite_excepción','string','No',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (5,'GESTION','','URL_excepcion','string','www.google.com',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (5,'GESTION','','URL_ejecucion','string','/api/FormularioObligacion/{id}/ejecutar',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
--Cuerpo de Bomberos
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (6,'GESTION','','tipo_generacion','string','Por tramite',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (6,'GESTION','','tiene_formulario','string','Si',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (6,'GESTION','','permite_excepción','string','No',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (6,'GESTION','','URL_excepcion','string','www.google.com',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (6,'GESTION','','URL_ejecucion','string','/api/FormularioObligacion/{id}/ejecutar',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
--Turismo
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (7,'GESTION','','tipo_generacion','string','Por tramite',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (7,'GESTION','','tiene_formulario','string','Si',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (7,'GESTION','','permite_excepción','string','No',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (7,'GESTION','','URL_excepcion','string','www.google.com',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (7,'GESTION','','URL_ejecucion','string','/api/FormularioObligacion/{id}/ejecutar',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
--Permiso Ambiental
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (8,'GESTION','','tipo_generacion','string','Manual',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (8,'GESTION','','tiene_formulario','string','No',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (8,'GESTION','','permite_excepción','string','No',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (8,'GESTION','','URL_excepcion','string','www.google.com',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (8,'GESTION','','URL_ejecucion','string','/api/FormularioObligacion/{id}/ejecutar',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
--Permiso Bienestar Animal
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (9,'GESTION','','tipo_generacion','string','Manual',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (9,'GESTION','','tiene_formulario','string','No',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (9,'GESTION','','permite_excepción','string','No',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (9,'GESTION','','URL_excepcion','string','www.google.com',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (9,'GESTION','','URL_ejecucion','string','/api/FormularioObligacion/{id}/ejecutar',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
--Tasa de Habilitación
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (10,'GESTION','','tipo_generacion','string','Por tramite',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (10,'GESTION','','tiene_formulario','string','No',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (10,'GESTION','','permite_excepción','string','No',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (10,'GESTION','','URL_excepcion','string','www.google.com',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');
INSERT INTO TmsObligacionCaracteristica (ObligacionId, Tipo, SubTipo, Nombre, TipoDato, Valor, Secuencia, Estado, FechaResgitro, UsuarioRegistro) VALUES (10,'GESTION','','URL_ejecucion','string','/api/FormularioObligacion/{id}/ejecutar',0,'ACTIVO',CURRENT_TIMESTAMP, 'admin@mail.com');